// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PluginListerExpansion allows custom methods to be added to
// PluginLister.
type PluginListerExpansion interface{}

// PluginNamespaceListerExpansion allows custom methods to be added to
// PluginNamespaceLister.
type PluginNamespaceListerExpansion interface{}
